<div class="page-title"><div><h1>Dokumen Resmi & Evidence</h1><p class="muted">Input dokumen dari BEI/OJK/IR emiten/IDX Data Service. Hanya dokumen berstatus confirmed yang boleh menjadi basis angka final.</p></div><button class="btn" data-modal-open="#sourceModal">Tambah Dokumen</button></div>
<section class="card"><div class="table-wrap"><table><thead><tr><th>Emiten</th><th>Jenis</th><th>Judul</th><th>Sumber</th><th>Periode</th><th>Verifikasi</th><th>File</th><th>Aksi</th></tr></thead><tbody>
<?php foreach($docs as $d): $json=e(json_encode($d,JSON_UNESCAPED_UNICODE)); ?>
<tr><td class="mono"><?= e($d['ticker'] ?? '-') ?></td><td><?= e($d['doc_type']) ?></td><td><?= e($d['title']) ?><br><span class="muted"><?= e($d['source_url']) ?></span></td><td><?= e($d['official_source']) ?><br><span class="muted">Publikasi: <?= e($d['published_date'] ?: '-') ?></span></td><td><?= e($d['period_start'] ?: '-') ?> — <?= e($d['period_end'] ?: '-') ?></td><td><?= badge($d['verification_status']) ?></td><td><?php if($d['file_path']): ?><span class="mono"><?= e(substr($d['file_checksum'],0,12)) ?></span><?php else: ?><span class="muted">-</span><?php endif; ?></td><td class="nowrap"><button class="btn small ghost" data-row='<?= $json ?>' onclick="fillSourceForm(this)">Edit</button><form method="post" action="<?= url('source.delete') ?>" style="display:inline" onsubmit="return confirmDelete()"><?= Csrf::input() ?><input type="hidden" name="id" value="<?= e($d['id']) ?>"><button class="btn small danger">Hapus</button></form></td></tr>
<?php endforeach; ?><?php if(!$docs): ?><tr><td colspan="8" class="muted">Belum ada dokumen.</td></tr><?php endif; ?></tbody></table></div></section>
<div class="modal" id="sourceModal"><div class="modal-dialog"><div class="modal-head"><h2>Form Dokumen Resmi</h2><button class="close" data-modal-close>×</button></div>
<form method="post" action="<?= url('source.save') ?>" enctype="multipart/form-data"><?= Csrf::input() ?><input type="hidden" name="id"><input type="hidden" name="existing_file_path"><input type="hidden" name="existing_checksum"><div class="form-grid">
<div class="field"><label>Emiten</label><select name="company_id"><option value="">Umum / non-emiten</option><?php foreach($companies as $c): ?><option value="<?= e($c['id']) ?>"><?= e($c['ticker'].' - '.$c['name']) ?></option><?php endforeach; ?></select></div>
<div class="field"><label>Jenis Dokumen</label><select name="doc_type"><option value="financial_statement">financial_statement</option><option value="annual_report">annual_report</option><option value="disclosure">disclosure</option><option value="rups">rups</option><option value="corporate_action">corporate_action</option><option value="public_expose">public_expose</option><option value="investor_presentation">investor_presentation</option><option value="price_weekly">price_weekly</option><option value="idx30_list">idx30_list</option><option value="suspension">suspension</option><option value="xbrl">xbrl</option><option value="other">other</option></select></div>
<div class="field full"><label>Judul</label><input name="title" required></div>
<div class="field"><label>Sumber Resmi</label><select name="official_source"><option value="IDX">IDX</option><option value="OJK">OJK</option><option value="Issuer_IR">Issuer_IR</option><option value="IDX_Data_Service">IDX_Data_Service</option><option value="Other_Official">Other_Official</option></select></div>
<div class="field"><label>Status Verifikasi</label><select name="verification_status"><option value="pending">pending</option><option value="confirmed">confirmed</option><option value="rejected">rejected</option></select></div>
<div class="field full"><label>URL Sumber</label><input name="source_url" placeholder="https://www.idx.co.id/... atau URL IR emiten resmi"></div>
<div class="field"><label>Tanggal Publikasi</label><input type="date" name="published_date"></div><div class="field"><label>Periode Mulai</label><input type="date" name="period_start"></div><div class="field"><label>Periode Akhir</label><input type="date" name="period_end"></div>
<div class="field"><label>Upload Dokumen</label><input type="file" name="document_file"></div>
<div class="field full"><label>Catatan Audit</label><textarea name="notes"></textarea></div>
</div><div class="actions"><button class="btn">Simpan Dokumen</button></div></form></div></div>
