<div class="page-title"><div><h1>Langkah 1 — Screening Seluruh Emiten BEI</h1><p class="muted">Screening otomatis hanya meloloskan saham dengan data confirmed, katalis verified, filter kuantitatif, DER/OCF, dan teknikal weekly valid.</p></div></div>
<section class="card">
  <form method="get" class="actions" style="margin-top:0"><input type="hidden" name="route" value="screening"><div class="field"><label>Pilih Siklus</label><select name="cycle_id" onchange="this.form.submit()"><?php foreach($cycles as $cy): ?><option value="<?= e($cy['id']) ?>" <?= $cycleId==$cy['id']?'selected':'' ?>><?= e($cy['cycle_code'].' · '.$cy['period_start'].'—'.$cy['period_end']) ?></option><?php endforeach; ?></select></div></form>
  <?php if($cycle): ?><div class="actions"><form method="post" action="<?= url('screening.run') ?>" onsubmit="return confirm('Jalankan screening ulang? Hasil screening lama untuk siklus ini akan diganti.')"><?= Csrf::input() ?><input type="hidden" name="cycle_id" value="<?= e($cycleId) ?>"><button class="btn">Jalankan Screening Siklus Ini</button></form><button class="btn ghost" data-modal-open="#catalystModal">Tambah Katalis</button><button class="btn ghost" data-modal-open="#techModal">Review Teknikal</button></div><?php endif; ?>
</section>
<section class="card">
  <h2>Top 5 Kandidat Terbaik</h2>
  <p class="muted">Jika PASS kurang dari 5, sistem tidak memaksa mengisi kandidat dengan saham yang tidak memenuhi syarat.</p>
  <?php if(count($top5)<5): ?><div class="alert warn">PASS saat ini <?= count($top5) ?>/5. Output final belum memenuhi ketentuan “tepat 5” tanpa melanggar hard constraint.</div><?php endif; ?>
  <div class="table-wrap"><table><thead><tr><th>#</th><th>Kode</th><th>Sektor</th><th>Status</th><th>Score</th><th>Data Pendukung</th></tr></thead><tbody>
  <?php foreach($top5 as $i=>$r): $snap=json_decode($r['data_snapshot'] ?: '{}',true); ?>
  <tr><td><?= $i+1 ?></td><td class="mono"><strong><?= e($r['ticker']) ?></strong><br><span class="muted"><?= e($r['name']) ?></span></td><td><?= e($r['sector']) ?></td><td><?= badge($r['status']) ?></td><td><strong><?= e($r['score']) ?></strong></td><td>Periode LK: <?= e($snap['latest_financial_period'] ?? 'DATA BELUM TERKONFIRMASI') ?><br>Revenue YoY: <?= e($snap['revenue_yoy_pct'] ?? 'DATA BELUM TERKONFIRMASI') ?>% · NP YoY: <?= e($snap['net_profit_yoy_pct'] ?? 'DATA BELUM TERKONFIRMASI') ?>%<br>DER: <?= e($snap['der'] ?? 'DATA BELUM TERKONFIRMASI') ?> · OCF: <?= e($snap['operating_cash_flow'] ?? 'DATA BELUM TERKONFIRMASI') ?><br>Weekly: <?= e($snap['technical']['week_end'] ?? '-') ?> · Vol Ratio <?= e($snap['technical']['volume_ratio20w'] ?? '-') ?>×</td></tr>
  <?php endforeach; ?><?php if(!$top5): ?><tr><td colspan="6" class="muted">Belum ada saham PASS.</td></tr><?php endif; ?>
  </tbody></table></div>
</section>
<section class="card"><h2>Semua Hasil Screening</h2><div class="table-wrap"><table><thead><tr><th>Kode</th><th>Status</th><th>Gate</th><th>Score</th><th>Alasan Drop / Catatan</th></tr></thead><tbody>
<?php foreach($results as $r): ?><tr><td class="mono"><strong><?= e($r['ticker']) ?></strong><br><span class="muted"><?= e($r['name']) ?></span></td><td><?= badge($r['status']) ?></td><td>Katalis <?= $r['catalyst_pass']?badge('PASS'):badge('FAIL') ?><br>Quant <?= $r['quantitative_pass']?badge('PASS'):badge('FAIL') ?><br>DER <?= $r['der_pass']?badge('PASS'):badge('FAIL') ?><br>OCF <?= $r['ocf_pass']?badge('PASS'):badge('FAIL') ?><br>Teknikal <?= $r['technical_pass']?badge('PASS'):badge('FAIL') ?></td><td><?= e($r['score']) ?></td><td><pre class="mono" style="white-space:pre-wrap;margin:0"><?= e($r['fail_reasons'] ?: '-') ?></pre></td></tr><?php endforeach; ?><?php if(!$results): ?><tr><td colspan="5" class="muted">Belum ada hasil. Jalankan screening setelah data masuk.</td></tr><?php endif; ?>
</tbody></table></div></section>
<div class="grid cols-2">
<section class="card"><h2>Katalis Tervalidasi Siklus</h2><div class="table-wrap"><table><thead><tr><th>Ticker</th><th>Jenis</th><th>Bukti</th><th>Flags</th><th>Status</th></tr></thead><tbody><?php foreach($catalysts as $ca): ?><tr><td class="mono"><?= e($ca['ticker']) ?></td><td><?= e($ca['catalyst_type']) ?></td><td><?= e($ca['description']) ?><br><span class="muted"><?= e($ca['evidence_summary']) ?></span></td><td>Core <?= $ca['impact_core_business']?'✓':'-' ?> · Repeat <?= $ca['repeatable']?'✓':'-' ?> · Scale <?= $ca['scalable']?'✓':'-' ?> · MultiQ <?= $ca['multi_quarter_impact']?'✓':'-' ?></td><td><?= $ca['verified']?badge('verified'):badge('pending') ?></td></tr><?php endforeach; ?><?php if(!$catalysts): ?><tr><td colspan="5" class="muted">Belum ada katalis.</td></tr><?php endif; ?></tbody></table></div></section>
<section class="card"><h2>Review Teknikal Manual</h2><div class="table-wrap"><table><thead><tr><th>Ticker</th><th>Minggu</th><th>Fase</th><th>Risk Flag</th><th>Catatan</th></tr></thead><tbody><?php foreach($techReviews as $t): ?><tr><td class="mono"><?= e($t['ticker']) ?></td><td><?= e($t['review_week_end']) ?></td><td><?= e($t['phase']) ?></td><td><?= $t['distribution_extreme']?badge('Distribusi'):'' ?> <?= $t['ath_without_new_catalyst']?badge('ATH tanpa katalis'):'' ?></td><td><?= e($t['relative_strength_notes']) ?></td></tr><?php endforeach; ?><?php if(!$techReviews): ?><tr><td colspan="5" class="muted">Belum ada review teknikal manual.</td></tr><?php endif; ?></tbody></table></div></section>
</div>
<div class="modal" id="catalystModal"><div class="modal-dialog"><div class="modal-head"><h2>Tambah Katalis Resmi</h2><button class="close" data-modal-close>×</button></div><form method="post" action="<?= url('catalyst.save') ?>"><?= Csrf::input() ?><input type="hidden" name="cycle_id" value="<?= e($cycleId) ?>"><div class="form-grid"><div class="field"><label>Emiten</label><select name="company_id" required><?php foreach($companies as $c): ?><option value="<?= e($c['id']) ?>"><?= e($c['ticker'].' - '.$c['name']) ?></option><?php endforeach; ?></select></div><div class="field"><label>Jenis Katalis</label><select name="catalyst_type"><option value="turnaround">Turnaround Terverifikasi</option><option value="innovation_disruption">Inovasi/Disrupsi Nyata</option><option value="measured_expansion">Ekspansi Masif & Terukur</option><option value="structural_trend">Benefisiari Tren Struktural</option></select></div><div class="field full"><label>Deskripsi Faktual</label><textarea name="description" required></textarea></div><div class="field full"><label>Bukti & Periode</label><textarea name="evidence_summary" required placeholder="Contoh: Revenue 1Q2026 tumbuh 28% YoY berdasarkan LK interim periode 31 Maret 2026."></textarea></div><div class="field full"><label>Dokumen Sumber Confirmed</label><select name="source_document_id"><option value="">DATA BELUM TERKONFIRMASI</option><?php foreach($sources as $s): ?><option value="<?= e($s['id']) ?>"><?= e($s['id'].' · '.$s['title']) ?></option><?php endforeach; ?></select></div><label><input type="checkbox" name="impact_core_business"> Dampak ke core business</label><label><input type="checkbox" name="repeatable"> Repeatable</label><label><input type="checkbox" name="scalable"> Scalable</label><label><input type="checkbox" name="multi_quarter_impact"> Multi-kuartal</label><label><input type="checkbox" name="verified"> Verified</label></div><div class="actions"><button class="btn">Simpan Katalis</button></div></form></div></div>
<div class="modal" id="techModal"><div class="modal-dialog"><div class="modal-head"><h2>Review Teknikal Weekly</h2><button class="close" data-modal-close>×</button></div><form method="post" action="<?= url('technical.save') ?>"><?= Csrf::input() ?><input type="hidden" name="cycle_id" value="<?= e($cycleId) ?>"><div class="form-grid"><div class="field"><label>Emiten</label><select name="company_id" required><?php foreach($companies as $c): ?><option value="<?= e($c['id']) ?>"><?= e($c['ticker'].' - '.$c['name']) ?></option><?php endforeach; ?></select></div><div class="field"><label>Review Week End</label><input type="date" name="review_week_end" required value="<?= e(date('Y-m-d')) ?>"></div><div class="field"><label>Fase Harga</label><select name="phase"><option value="base">base</option><option value="breakout">breakout</option><option value="re_accumulation">re_accumulation</option><option value="downtrend">downtrend</option><option value="distribution">distribution</option><option value="unconfirmed">unconfirmed</option></select></div><div class="field"><label>Dokumen Sumber Harga</label><select name="source_document_id"><option value="">DATA BELUM TERKONFIRMASI</option><?php foreach($sources as $s): ?><option value="<?= e($s['id']) ?>"><?= e($s['id'].' · '.$s['title']) ?></option><?php endforeach; ?></select></div><label><input type="checkbox" name="distribution_extreme"> Distribusi ekstrem</label><label><input type="checkbox" name="ath_without_new_catalyst"> ATH tanpa katalis baru</label><div class="field full"><label>Catatan Relative Strength</label><textarea name="relative_strength_notes"></textarea></div><div class="field full"><label>Catatan Analyst</label><textarea name="analyst_notes"></textarea></div></div><div class="actions"><button class="btn">Simpan Review</button></div></form></div></div>
