<div class="page-title"><div><h1>Langkah 2 — Five-Pillar Validation & Investment Memo</h1><p class="muted">Prinsip: mencari alasan untuk membatalkan ide. ≥2 pilar gagal = DROP otomatis.</p></div></div>
<section class="card"><form method="get" class="actions" style="margin-top:0"><input type="hidden" name="route" value="memos"><div class="field"><label>Siklus</label><select name="cycle_id" onchange="this.form.submit()"><?php foreach($cycles as $cy): ?><option value="<?= e($cy['id']) ?>" <?= $cycleId==$cy['id']?'selected':'' ?>><?= e($cy['cycle_code']) ?></option><?php endforeach; ?></select></div><div class="field"><label>Emiten</label><select name="company_id" onchange="this.form.submit()"><?php foreach($companies as $c): ?><option value="<?= e($c['id']) ?>" <?= $selectedCompanyId==$c['id']?'selected':'' ?>><?= e($c['ticker'].' · '.$c['screening_status'].' · score '.$c['score']) ?></option><?php endforeach; ?></select></div></form></section>
<?php if($company): ?>
<div class="grid cols-2">
<section class="card"><h2><?= e($company['ticker'].' - '.$company['name']) ?></h2><div class="kpi-list"><div><span>Sektor</span><strong><?= e($company['sector']) ?></strong></div><div><span>Status Screening</span><strong><?php $sc=array_values(array_filter($companies,fn($c)=>$c['id']==$company['id']))[0] ?? null; echo $sc?badge($sc['screening_status']):badge('DATA_BELUM_TERKONFIRMASI'); ?></strong></div></div><div class="actions"><form method="post" action="<?= url('memo.generate') ?>"><?= Csrf::input() ?><input type="hidden" name="cycle_id" value="<?= e($cycleId) ?>"><input type="hidden" name="company_id" value="<?= e($selectedCompanyId) ?>"><button class="btn">Generate / Update Memo</button></form></div></section>
<section class="card"><h2>Decision Gate Final</h2><div class="pillars"><?php foreach(['catalyst'=>'Katalis','financial_quality'=>'Finansial','moat'=>'Moat','technical'=>'Teknikal','risk_reward'=>'Risk–Reward'] as $key=>$label): $p=$pillarMap[$key]??null; ?><div class="pillar-card"><strong><?= e($label) ?></strong><br><?= $p?badge($p['status']):badge('DATA_BELUM_TERKONFIRMASI') ?></div><?php endforeach; ?></div><?php if($valuation): ?><p class="muted">RR Ratio: <?= e($valuation['upside_downside_ratio'] ?? 'DATA BELUM TERKONFIRMASI') ?> · Periode valuasi: <?= e($valuation['period_end']) ?></p><?php endif; ?></section>
</div>
<section class="card"><h2>Input / Update Pilar Validasi</h2><form method="post" action="<?= url('pillar.save') ?>"><?= Csrf::input() ?><input type="hidden" name="cycle_id" value="<?= e($cycleId) ?>"><input type="hidden" name="company_id" value="<?= e($selectedCompanyId) ?>"><div class="form-grid"><div class="field"><label>Pilar</label><select name="pillar"><option value="catalyst">Pilar 1 — Validasi Katalis</option><option value="financial_quality">Pilar 2 — Finansial & Kualitas Laba</option><option value="moat">Pilar 3 — Positioning & Moat</option><option value="technical">Pilar 4 — Teknikal Strategis Weekly</option><option value="risk_reward">Pilar 5 — Valuasi & Asymmetric Return</option></select></div><div class="field"><label>Status</label><select name="status"><option value="LULUS">LULUS</option><option value="GAGAL">GAGAL</option><option value="TUNDA">TUNDA</option></select></div><div class="field full"><label>Tesis ≤3 Kalimat / Analisis Pilar</label><textarea name="thesis" placeholder="Tuliskan tesis berbasis dokumen, bukan opini."></textarea></div><div class="field full"><label>Indikator Keberhasilan Terukur</label><textarea name="success_indicators"></textarea></div><div class="field full"><label>Indikator Kegagalan / Early Warning</label><textarea name="failure_indicators"></textarea></div><div class="field full"><label>Catatan Analisis</label><textarea name="analysis_notes"></textarea></div><div class="field full"><label>Dokumen Sumber Confirmed</label><select name="source_document_id"><option value="">DATA BELUM TERKONFIRMASI</option><?php foreach($sources as $s): ?><option value="<?= e($s['id']) ?>"><?= e($s['id'].' · '.$s['title']) ?></option><?php endforeach; ?></select></div></div><div class="actions"><button class="btn">Simpan Pilar</button></div></form></section>
<div class="grid cols-2">
<section class="card"><h2>Daftar Pilar</h2><div class="table-wrap"><table><thead><tr><th>Pilar</th><th>Status</th><th>Tesis</th><th>Early Warning</th></tr></thead><tbody><?php foreach($pillars as $p): ?><tr><td><?= e($p['pillar']) ?></td><td><?= badge($p['status']) ?></td><td><?= e($p['thesis']) ?></td><td><?= e($p['failure_indicators']) ?></td></tr><?php endforeach; ?><?php if(!$pillars): ?><tr><td colspan="4" class="muted">Belum ada validasi pilar.</td></tr><?php endif; ?></tbody></table></div></section>
<section class="card"><h2>Valuasi & Asymmetric Return</h2><form method="post" action="<?= url('valuation.save') ?>"><?= Csrf::input() ?><input type="hidden" name="cycle_id" value="<?= e($cycleId) ?>"><input type="hidden" name="company_id" value="<?= e($selectedCompanyId) ?>"><div class="form-grid"><div class="field"><label>Periode Valuasi</label><input type="date" name="period_end" value="<?= e($valuation['period_end'] ?? date('Y-m-d')) ?>"></div><div class="field"><label>Current Price</label><input name="current_price" value="<?= e($valuation['current_price'] ?? '') ?>"></div><div class="field"><label>Bear Price</label><input name="bear_price" value="<?= e($valuation['bear_price'] ?? '') ?>"></div><div class="field"><label>Base Price</label><input name="base_price" value="<?= e($valuation['base_price'] ?? '') ?>"></div><div class="field"><label>Bull Price / Conservative Target</label><input name="bull_price" value="<?= e($valuation['bull_price'] ?? '') ?>"></div><div class="field"><label>Dokumen Sumber</label><select name="source_document_id"><option value="">DATA BELUM TERKONFIRMASI</option><?php foreach($sources as $s): ?><option value="<?= e($s['id']) ?>" <?= (($valuation['source_document_id']??'')==$s['id'])?'selected':'' ?>><?= e($s['id'].' · '.$s['title']) ?></option><?php endforeach; ?></select></div><div class="field full"><label>Valuasi Relatif: PER / EV-EBITDA</label><textarea name="valuation_relative"><?= e($valuation['valuation_relative'] ?? '') ?></textarea></div><label><input type="checkbox" name="is_confirmed" <?= !empty($valuation['is_confirmed'])?'checked':'' ?>> Valuasi confirmed & sumber valid</label></div><div class="actions"><button class="btn">Simpan Valuasi</button></div></form><?php if($valuation): ?><div class="note">Downside: <?= e($valuation['downside_pct']) ?>% · Upside konservatif: <?= e($valuation['conservative_upside_pct']) ?>% · Ratio: <?= e($valuation['upside_downside_ratio']) ?>×</div><?php endif; ?></section>
</div>
<?php if($memo): ?>
<section class="card"><h2>Investment Memo Final</h2><div class="note"><strong>Status Akhir:</strong> <?= badge($memo['final_status']) ?> · <?= e($memo['decision_reason']) ?></div><h3>Ringkasan Tesis</h3><p><?= nl2br(e($memo['summary_thesis'])) ?></p><h3>Data Kunci + Periode</h3><p><?= nl2br(e($memo['key_data'])) ?></p><h3>Katalis Tervalidasi</h3><p><?= nl2br(e($memo['validated_catalyst'])) ?></p><h3>Risiko Utama</h3><p><?= nl2br(e($memo['main_risks'])) ?></p><h3>Level Invalidasi</h3><p><?= nl2br(e($memo['invalidation_level'])) ?></p></section>
<?php endif; ?>
<?php else: ?><section class="card"><p class="muted">Belum ada emiten pada siklus ini. Jalankan screening terlebih dahulu.</p></section><?php endif; ?>
